config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  resources :races, only: [:index, :new, :create, :show] do
    get :run
  end

  root to: "races#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/delayedjob_player.rb
class DelayedjobPlayer < Player
  has_one :race, class_name: "Race", foreign_key: "delayedjob_player_id"

  def run
    Delayed::Job.enqueue(DelayedjobRacer.new(id))
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :steps

  def self.advance player_id
    player = find(player_id)
    player.steps << Step.create(player: player)
  end

  def run
    raise "Implement in child class"
  end

  def done?
    position >= race.distance
  end

  def position
    steps.length
  end

  def finish_time
    steps.maximum(:created_at)
  end

  def start_time
    steps.minimum(:created_at)
  end

  def duration
    finish_time - start_time
  end
end

app/models/race.rb
class Race < ApplicationRecord
  belongs_to :sidekiq_player,     class_name: "SidekiqPlayer"
  belongs_to :delayedjob_player,  class_name: "DelayedjobPlayer"

  default_scope {  includes(:sidekiq_player)
                  .includes(:delayedjob_player)
                  .order(created_at: :desc) }

  validates :distance, presence: true

  def self.start opts={}
    race                    = new(opts)
    race.sidekiq_player     = SidekiqPlayer.new
    race.delayedjob_player  = DelayedjobPlayer.new
    race.save!

    RaceRunner.perform_async(race.id)
    race
  end

  def run
    distance.times do
      sidekiq_player.run
      delayedjob_player.run
    end
  end

  def done?
    sidekiq_player.done? || delayedjob_player.done?
  end

  def winner
    if done?
      if sidekiq_player.finish_time < delayedjob_player.finish_time
        "sidekiq"
      elsif sidekiq_player.finish_time > delayedjob_player.finish_time
        "delayedjob"
      else
        "tie"
      end
    end
  end

  def loser
    if done?
      if sidekiq_player.finish_time > delayedjob_player.finish_time
        "sidekiq"
      elsif sidekiq_player.finish_time < delayedjob_player.finish_time
        "delayedjob"
      else
        "tie"
      end
    end
  end

  def duration_percentage
    send("#{winner}_player".to_sym).duration / send("#{loser}_player".to_sym).duration * 100
  end
end

app/models/sidekiq_player.rb
class SidekiqPlayer < Player
  has_one :race, class_name: "Race", foreign_key: "sidekiq_player_id"

  def run
    SidekiqRacer.perform_async(id)
  end
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :player
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/races_controller.rb
class RacesController < ApplicationController

  def index
    @races = Race.all
  end

  def new
    @race = Race.new
  end

  def create
    redirect_to race_path(Race.start(params.require(:race).permit(:distance)).id)
  rescue => e
    Rails.logger.error e.message
    Rails.logger.error e.backtrace.join("\n\t")

    flash[:error] = "Unable to start race: #{e.message}"
    redirect_to new_race_path
  end

  def show
    @race = Race.find(params[:id])
  end

  def run
    @race = Race.find(params[:race_id])
    render json: @race
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/races_helper.rb
module RacesHelper

  def format_racer race, player
    if race.winner == player
      "winner"
    elsif race.loser == player
      "loser"
    else
      ""
    end
  end
end

app/views/layouts/_flash.html.erb
<% unless flash.empty? %>
  <% flash.each do |name, msg| %>
    <div class="alert callout" data-closable>
      <%= msg.html_safe %>
      <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <% flash.clear %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Ready, Set, Go!</title>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": true %>
    <%= csrf_meta_tags %>
    <%= yield :head %>
  </head>

  <body>
    <div class="row columns header">
      <h1>Ready, Set, Go!</h1>
    </div>
    <div id="flash-container" class="row columns small-8 small-offset-2">
      <%= render partial: "layouts/flash" %>
    </div>
    <div class="row columns">
      <%= yield %>
    </div>

    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= yield :after_javascript %>
  </body>
</html>

app/views/races/_form.html.erb
<div class="row">
  <div class="columns">
    <%= form_for(@race) do |f| %>
      <div class="row" data-equalizer>
        <div class="small-3 columns" data-equalizer-watch>
          <%= f.label :distance, "How far are we going today?", class: "middle" %>
        </div>
        <div class="small-6 columns" data-equalizer-watch>
          <%= f.number_field :distance, placeholder: "every step counts" %>
        </div>
        <div class="small-3 columns" data-equalizer-watch>
          <%= f.submit "Go!", class: "go button" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/races/_lane.html.erb
<div class="row <%= player %>-player-container">
  <div class="columns">
    <%= image_tag "#{player}-player.gif", class: "#{player}-player" %>
  </div>
</div>

app/views/races/index.html.erb
<div class="row columns new-race">
  <%= link_to "New Race", new_race_path, class: "button" %>
</div>
<div class="row columns">
  <table class="races-table">
    <thead>
      <tr>
        <th class="text-center" width="10%">#</th>
        <th width="10%">Distance</th>
        <th width="20%">Start Time</th>
        <th width="20%">Sidekiq Finish</th>
        <th width="20%">Delayed Job Finish</th>
        <th width="15%">Time Diff (s)</th>
        <th width="15%">% Diff</th>
      </tr>
    </thead>
    <tbody class="races">
      <% @races.each do |race| %>
        <tr class="race-row" data-href="<%= race_path(race) %>">
          <td class="text-center">
            <%= race.id %>
          </td>
          <td class="text-right">
            <%= race.distance %>
          </td>
          <td class="text-center %>">
            <%= race.created_at.strftime("%m/%d/%y %H:%M:%S") %>
          </td>
          <td class="text-center <%= format_racer(race, "sidekiq") %>">
            <%= race.sidekiq_player.finish_time.strftime("%m/%d/%y %H:%M:%S") %>
          </td>
          <td class="text-center <%= format_racer(race, "delayedjob") %>">
            <%= race.delayedjob_player.finish_time.strftime("%m/%d/%y %H:%M:%S") %>
          </td>
          <td class="text-right">
            <%= race.sidekiq_player.finish_time - race.delayedjob_player.finish_time %>
          </td>
          <td class="text-right">
            <%= "%.2f" % race.duration_percentage %>%
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="row columns new-race">
  <%= link_to "New Race", new_race_path, class: "button" %>
</div>

<% content_for :after_javascript do %>
  <script type="text/javascript">
    $("tbody.races").on("click", "tr.race-row", function () {
       window.document.location = $(this).data("href");
    })
  </script>
<% end %>

app/views/races/new.html.erb
<%= render partial: "form" %>
<div class="row columns"><hr/></div>
<%= render partial: "lane", locals: { player: "sidekiq" } %>
<div class="row columns"><hr/></div>
<%= render partial: "lane", locals: { player: "delayedjob" } %>
<div class="row columns"><hr/></div>

app/views/races/show.html.erb
<div class="row">
  <div class="columns">
    <div class="row" data-equalizer>
      <div class="small-3 columns" data-equalizer-watch>
        <h4>And they're off...<h4>
      </div>
      <div class="small-6 columns" data-equalizer-watch>
        <h4>Distance: <%= @race.distance %><h4>
      </div>
      <div class="small-3 columns" data-equalizer-watch>
        <%= link_to "View Results", races_path, class: "button" %>
        <%= link_to "New Race", new_race_path, class: "button secondary" %>
      </div>
    </div>
  </div>
</div>
<div class="row columns"><hr/></div>
<%= render partial: "lane", locals: { player: "sidekiq" } %>
<div class="row columns"><hr/></div>
<%= render partial: "lane", locals: { player: "delayedjob" } %>
<div class="row columns"><hr/></div>

<% content_for :after_javascript do %>
  <script type="text/javascript">

    var calculateMovement = function (position, distance) {
      var placement = ((position/distance) * 85).toString() + "%"
      return placement
    }

    var refreshPage = function () {
      var sidekiq_done    = false
      var delayedjob_done = false

      $.ajax({
        url: "<%= race_run_path(@race.id) %>"
      }).done(function (data) {
        console.log(data)
        sidekiq_done    = data.sidekiq_player     >= data.distance
        delayedjob_done = data.delayedjob_player  >= data.distance

        $(".sidekiq-player").animate({
          marginLeft: calculateMovement(data.sidekiq_player, data.distance)
        }, 5000)

        $(".delayedjob-player").animate({
          marginLeft: calculateMovement(data.delayedjob_player, data.distance)
        }, 5000)

        if (sidekiq_done && !delayedjob_done) {
          $(".sidekiq-player").addClass("winner")
          $(".delayedjob-player").addClass("loser")
        }

        if (!sidekiq_done && delayedjob_done) {
          $(".sidekiq-player").addClass("loser")
          $(".delayedjob-player").addClass("winner")
        }

        if (!sidekiq_done || !delayedjob_done) {
          setTimeout(refreshPage, 5000)
        }
      })
    }

    refreshPage()
  </script>
<% end %>